apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: goapp
spec:
  image: aditirvan/goapp
  interval: 1m0s
  secretRef:
    name: dockerhub-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: goapp
spec:
  imageRepositoryRef:
    name: goapp
  policy:
    numerical:
      order: asc