apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 1m0s
  url: https://grafana.github.io/helm-charts

# helm repo add grafana https://grafana.github.io/helm-charts