apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
  - namespace.yaml
  - ../../../../helm/ingress-nginx/repository.yaml
  # - ingress-nginx
  # - test-melawikab-go-id.yaml