apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      # imagePullSecrets:
      # - name: dockerhub-secret
      containers:
      - name: webapp
        image: rudicatsmile2/belajar-cicd:1 # {"$imagepolicy": "flux-system:webapp"} ....
        # image: rudicatsmile2/biodata-webapp:1 # {"$imagepolicy": "flux-system:webapp"} ....
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
