apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      # imagePullSecrets:
      # - name: dockerhub-secret   
      containers:
      - name: simpleapp
        image: rudicatsmile2/biodata-webapp:1 # {"$imagepolicy": "flux-system:simpleapp"} ....
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
