apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
spec:
  interval: 1m0s
  url: https://charts.jetstack.io

# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx